pipelines:
  mps-allowancesdb:
    group: common
    label_template: "${COUNT}"
    materials:
      mps-allowancesdb-git:
        git: https://github.com/ukparliament/mpsallowancesdb.parliament.uk.git
        branch: development
        auto_update: true
    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release

environments:
  WebDEVCI:
    pipelines:
      - mps-allowancesdb
