pipelines:
  mps-allowancesdb:
    group: Static-Websites
    label_template: "${COUNT}"
    materials:
      mps-allowancesdb-git:
        git: https://github.com/ukparliament/mpsallowancesdb.parliament.uk.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          approval: manual
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - checkout_to_release
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release

environments:
  WebLIVE:
    pipelines:
      - mps-allowancesdb
